### **Nigeria Health Facilities and Population Data ETL**

In [97]:
# importing dependencies

import pandas as pd

print(pd.__version__)

3.0.0

In [98]:
# importing the dataset

nhf = pd.read_csv('nigeriahealthfacilities.csv', encoding_errors='ignore')
population_data = pd.read_csv('nga_admpop_adm1_2022.csv', encoding_errors='ignore')

print(nhf.shape)
print(population_data.shape)

(46146, 15)
(37, 60)

In [99]:
# this shows the first 5 rows of the dataset

nhf.head()

,id,name,global_id,alternate_name,functional_status,type,ward_code,category,timestamp,accessibility,lga_name,lga_code,state_code,state_name,FID
0,1,G R A Nursing Home,af719462-abfd-4f47-9dc3-0987164e75ac,Nursing Home,Unknown,Primary,12413,Primary Health Center,2020-07-04T13:49:18Z,NaN,Maiduguri,124,BR,Borno,sv_health_facilities.fid--3185df38_17a314b4ee6...
1,2,Gishili Health Center,a29b0328-d844-4358-b0ab-2e120b8fb30f,Nursing Home,Functional,Primary,12413,Primary Health Center,2020-07-04T13:49:18Z,Unknown,Maiduguri,124,BR,Borno,sv_health_facilities.fid--3185df38_17a314b4ee6...
2,3,Lehobi Primary Health Care,b685b769-5c83-4f83-a182-00e7e1b777d8,NaN,Partially Functional,Primary,10207,Primary Health Center,2020-07-04T13:49:18Z,NaN,Askira Uba,102,BR,Borno,sv_health_facilities.fid--3185df38_17a314b4ee6...
3,4,Dugja Idp Camp,78e64f7a-cbb8-4357-9e64-a7e502534527,Mandara Girau Dispensary,Not Functional,Primary,10503,Primary Health Center,2020-07-04T13:49:18Z,Unknown,Biu,105,BR,Borno,sv_health_facilities.fid--3185df38_17a314b4ee6...
4,5,Kopa Maikudiri Dispensary,409c97ce-7490-4dc2-a8f8-2b8d53ad2b12,NaN,Partially Functional,Primary,10209,Dispensary,2020-07-04T13:49:18Z,Unknown,Askira Uba,102,BR,Borno,sv_health_facilities.fid--3185df38_17a314b4ee6...

In [100]:
nhf.columns

Index(['id', 'name', 'global_id', 'alternate_name', 'functional_status',
       'type', 'ward_code', 'category', 'timestamp', 'accessibility',
       'lga_name', 'lga_code', 'state_code', 'state_name', 'FID'],
      dtype='str')

In [101]:
population_data.head()

,year,ISO3,ADM0_EN,ADM0_PCODE,ADM1_EN,ADM1_PCODE,F_TL,M_TL,T_TL,F_00_04,...,T_35_39,T_40_44,T_45_49,T_50_54,T_55_59,T_60_64,T_65_69,T_70_74,T_75_79,T_80Plus
0,2022,NGA,Nigeria,NG,Abia,NG001,2094668,2048425,4143093,335552,...,270125,229591,176320,141298,121309,97411,68694,45777,26675,20739
1,2022,NGA,Nigeria,NG,Adamawa,NG002,2446708,2455347,4902055,414427,...,268517,230240,177408,138267,106544,79108,52503,32993,18448,13876
2,2022,NGA,Nigeria,NG,Akwa Ibom,NG003,2487982,2491436,4979418,305461,...,341908,294305,231221,187639,161876,129446,87245,56689,34820,24141
3,2022,NGA,Nigeria,NG,Anambra,NG004,2983151,2970366,5953517,437103,...,396147,339238,258269,205621,176534,140589,96470,62587,35772,25957
4,2022,NGA,Nigeria,NG,Bauchi,NG005,4160248,4148535,8308783,772241,...,382409,324094,253016,197570,149279,109280,71973,44771,24414,18227

In [102]:
population_data.columns

Index(['year', 'ISO3', 'ADM0_EN', 'ADM0_PCODE', 'ADM1_EN', 'ADM1_PCODE',
       'F_TL', 'M_TL', 'T_TL', 'F_00_04', 'F_05_09', 'F_10_14', 'F_15_19',
       'F_20_24', 'F_25_29', 'F_30_34', 'F_35_39', 'F_40_44', 'F_45_49',
       'F_50_54', 'F_55_59', 'F_60_64', 'F_65_69', 'F_70_74', 'F_75_79',
       'F_80Plus', 'M_00_04', 'M_05_09', 'M_10_14', 'M_15_19', 'M_20_24',
       'M_25_29', 'M_30_34', 'M_35_39', 'M_40_44', 'M_45_49', 'M_50_54',
       'M_55_59', 'M_60_64', 'M_65_69', 'M_70_74', 'M_75_79', 'M_80Plus',
       'T_00_04', 'T_05_09', 'T_10_14', 'T_15_19', 'T_20_24', 'T_25_29',
       'T_30_34', 'T_35_39', 'T_40_44', 'T_45_49', 'T_50_54', 'T_55_59',
       'T_60_64', 'T_65_69', 'T_70_74', 'T_75_79', 'T_80Plus'],
      dtype='str')

In [103]:
population_data['year'].unique()

array([2022])

In [104]:
# column selection for only the relevant columns for analysis

selected_columns = ['year','ADM1_EN', 'T_TL',]
population_data = population_data[selected_columns]

In [105]:
# renaming the columns to aid in joining in sql

population_data.rename(columns={'ADM1_EN': 'state_name', 'T_TL': 'total_population'}, inplace=True)

In [106]:
population_data['state_name'].unique()

<StringArray>
[                     'Abia',                   'Adamawa',
                 'Akwa Ibom',                   'Anambra',
                    'Bauchi',                   'Bayelsa',
                     'Benue',                     'Borno',
               'Cross River',                     'Delta',
                    'Ebonyi',                       'Edo',
                     'Ekiti',                     'Enugu',
 'Federal Capital Territory',                     'Gombe',
                       'Imo',                    'Jigawa',
                    'Kaduna',                      'Kano',
                   'Katsina',                     'Kebbi',
                      'Kogi',                     'Kwara',
                     'Lagos',                  'Nasarawa',
                     'Niger',                      'Ogun',
                      'Ondo',                      'Osun',
                       'Oyo',                   'Plateau',
                    'Rivers',                    'Sokoto',
                    'Taraba',                      'Yobe',
                   'Zamfara']
Length: 37, dtype: str

In [107]:
nhf.info()

<class 'pandas.DataFrame'>
RangeIndex: 46146 entries, 0 to 46145
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 46146 non-null  int64
 1   name               46146 non-null  str
 2   global_id          46146 non-null  str
 3   alternate_name     4026 non-null   str
 4   functional_status  46146 non-null  str
 5   type               46146 non-null  str
 6   ward_code          46146 non-null  str
 7   category           46112 non-null  str
 8   timestamp          46146 non-null  str
 9   accessibility      134 non-null    str
 10  lga_name           46146 non-null  str
 11  lga_code           46146 non-null  int64
 12  state_code         45020 non-null  str
 13  state_name         46146 non-null  str
 14  FID                46146 non-null  str
dtypes: int64(2), str(13)
memory usage: 5.3 MB

In [108]:
population_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              37 non-null     int64
 1   state_name        37 non-null     str
 2   total_population  37 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1020.0 bytes

In [109]:
# this shows the statistical summary of the dataset

nhf.describe()

                 id      lga_code
count  46146.000000  46146.000000
mean   23311.124236  15658.749187
std    13467.929371  11386.058136
min        1.000000    101.000000
25%    11632.250000   4016.000000
50%    23315.500000  16002.000000
75%    34995.750000  26013.000000
max    46608.000000  35016.000000

In [110]:
nhf.duplicated().sum()

np.int64(0)

In [111]:
nhf.duplicated(subset=['id']).sum()

np.int64(0)

In [112]:
nhf.shape

(46146, 15)

In [113]:
nhf.isnull().sum()

id                       0
name                     0
global_id                0
alternate_name       42120
functional_status        0
type                     0
ward_code                0
category                34
timestamp                0
accessibility        46012
lga_name                 0
lga_code                 0
state_code            1126
state_name               0
FID                      0
dtype: int64

In [114]:
nhf.drop(columns=['alternate_name'], inplace=True)

# The alternate_name variable is removed because it contains a high proportion of missing values and is not relevant in the analysis of healthcare facilities in Nigeria.

In [115]:
# validating

nhf['category'].value_counts(dropna=False)

category
Primary Health Center               28031
Dispensary                           8626
Maternity Home                       4423
Private Non Profit                   1179
Medical Center                        956
Specialist Hospital                   673
General Hospital                      637
Comprehensive Health Center           458
Educational Clinic                    249
Laboratory                            234
Cottage Hospital                      223
Military and Paramilitary Clinic      143
Federal Staff Clinic                  110
Teaching Hospital                      51
Federal Medical Center                 46
NaN                                    34
District Hospital                      25
Pharmacy                               21
Veterinary Clinic                      14
Community Health Center                 8
Others                                  4
Research Hospital                       1
Name: count, dtype: int64

In [116]:
nhf['category'] = nhf['category'].fillna('Unknown')

# Missing values filled with 'Unknown' to ensure that all healthcare facilities are accounted for in the analysis.

In [117]:
nhf['accessibility'].value_counts(dropna=False)

accessibility
NaN        46012
Unknown      117
Yes           17
Name: count, dtype: int64

In [118]:
nhf['accessibility'].value_counts(dropna=False, normalize=True) * 100

accessibility
NaN        99.709617
Unknown     0.253543
Yes         0.036840
Name: proportion, dtype: float64

In [119]:
nhf.drop(columns=['accessibility'], inplace=True)

# The accessibility variable is excluded from the analysis because over 99% of its values are missing, making it unsuitable for meaningful analysis..

Note: pandas regarded the statecode "NA" as NAN hence indicating blank rows for Nasarawa state when in real sense, the rows are not blank.

In [120]:
nhf.isnull().sum()

id                      0
name                    0
global_id               0
functional_status       0
type                    0
ward_code               0
category                0
timestamp               0
lga_name                0
lga_code                0
state_code           1126
state_name              0
FID                     0
dtype: int64

In [121]:
nhf['state_name'].unique()

<StringArray>
[      'Borno',       'Benue',      'Bauchi',        'Ogun',     'Zamfara',
        'Kogi',        'Yobe',        'Abia',      'Ebonyi',         'Edo',
       'Ekiti',         'Imo',       'Kebbi',     'Plateau',       'Lagos',
       'Niger',      'Rivers',     'Adamawa',         'Oyo',       'Kwara',
     'Anambra',        'Osun',      'Sokoto',       'Enugu',       'Gombe',
     'Bayelsa',        'Ondo',       'Delta',      'Kaduna',    'Nasarawa',
     'Katsina',      'Jigawa', 'Cross River',         'Fct',      'Taraba',
        'Kano',   'Akwa Ibom']
Length: 37, dtype: str

In [122]:
nhf['state_name'] = nhf['state_name'].replace({'Fct': 'Federal Capital Territory'})

In [123]:
nhf['state_name'].unique()

<StringArray>
[                    'Borno',                     'Benue',
                    'Bauchi',                      'Ogun',
                   'Zamfara',                      'Kogi',
                      'Yobe',                      'Abia',
                    'Ebonyi',                       'Edo',
                     'Ekiti',                       'Imo',
                     'Kebbi',                   'Plateau',
                     'Lagos',                     'Niger',
                    'Rivers',                   'Adamawa',
                       'Oyo',                     'Kwara',
                   'Anambra',                      'Osun',
                    'Sokoto',                     'Enugu',
                     'Gombe',                   'Bayelsa',
                      'Ondo',                     'Delta',
                    'Kaduna',                  'Nasarawa',
                   'Katsina',                    'Jigawa',
               'Cross River', 'Federal Capital Territory',
                    'Taraba',                      'Kano',
                 'Akwa Ibom']
Length: 37, dtype: str

In [124]:
nhf.dtypes

id                   int64
name                   str
global_id              str
functional_status      str
type                   str
ward_code              str
category               str
timestamp              str
lga_name               str
lga_code             int64
state_code             str
state_name             str
FID                    str
dtype: object

In [125]:
nhf.to_csv('cleaned_nigeriahealthfacilities.csv', index=False)
population_data.to_csv('cleaned_population_data.csv', index=False)

In [126]:
# Loading the cleaned data into PostgreSQL database for further analysis using SQL queries 

from sqlalchemy import create_engine


engine = create_engine("postgresql+psycopg2://postgres:245074@localhost:5432/facility-to-population_ratio_analysis")

try:
    engine
    print('connection successful')
except:
    print('unable to connect')

connection successful

In [33]:
#exporting data to postgreSQL

nhf.to_sql(name= 'nigeriahealthfacilities', con=engine, if_exists='replace', index=False)
population_data.to_sql(name= 'populationdata', con=engine, if_exists='replace', index=False )

37